### ISSUE TITLE
take screenshots and download all files/content from current live URL

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-gbaqua#4]
gbaqua.com

same thing I had you do for a lot of our other sites. 

upload all assets to the appropriate google drive

due:
10-19-15     4p

**Comment by rodneystrong** [comment]
Reassigning to you @vanderbeam . @purplyrocky has a conflicting deadline that she has to focus on. 

Since this is already past due, please make this your priority or second priority if possible. If you have a question about another conflicting priority please email me and we can work it out.

**Comment by vanderbeam** [comment]
@rodneystrong  Phew! This site reminds me of those maps that shows all the inbound/outbound flights for airports. 

Everything should be there:
https://drive.google.com/folderview?id=0B7-L_YWYH3_YM3o3eFp2empYbFU&usp=sharing

The links on the Home page are the links on the top nav. All the items on the Specialty Products drop down all link to the same page (which is why there's not a folder for each one).

**Comment by rodneystrong** [comment]
Excellent work meg. I checked a few of the folders and they look good; i trust you on the rest.

**Comment by purplyrocky** [comment]
Hey thanks, Meg for taking care of this!
